apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: game-server-attackprocessed
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: attackprocessed
  subscriber:
    uri: http://game-server.frontend.svc.cluster.local:8080/event/trigger
